### ISSUE TITLE
Visual design basic mockup

### ISSUE THREAD

**Issue by RamanSel** [torontojs/speakfriend#8]
I have made this mock-up to help us understand what will the final project will look like. 

I would appreciate any feedback.

Please be constructive and if you feel that something needs to be changed or added, you can message me on TorontoJs slack, @Raman S.

Link for prototype is :
https://www.figma.com/proto/S8IRaq2gBmrpNzzNVGrsAzFD/Untitled?node-id=0%3A1&scaling=min-zoom

**Comment by zhonghaoliu** [comment]
@RamanSel There's #projects-speakfriend channel on TorontoJS slack, you may wanna share it there so more people could see it.

**Comment by RamanSel** [comment]
https://www.figma.com/proto/S8IRaq2gBmrpNzzNVGrsAzFD/Untitled?node-id=38%3A53&scaling=min-zoom
version 2
